#%RAML 1.0 Library
usage:
traits:
  transactionId: !include libraries/common/traits/headerstransactionIdtrait.raml
  departureLocationCode: !include libraries/common/traits/queryparamDepartureLocationtrait.raml
  arrivalLocationCode: !include libraries/common/traits/queryParamsarrivalLocationCodetrait.raml
